/**
 * Monologg data model — PRD §6 (region-aware, escrow-driven).
 * Fees are config, never literals (Conflict Ledger C1–C3).
 */

export type UserType = 'talent' | 'client';

export type Niche =
  | 'actor'
  | 'vo_artist'
  | 'comedian'
  | 'compere' // Core 4
  | 'speaker_pastor'
  | 'musician'
  | 'content_creator'; // Extended

export type MediaKind = 'video' | 'audio';

export type BookingState = 'escrow_locked' | 'deliverables_provided' | 'payment_released';

export type VerificationState = 'unverified' | 'processing' | 'verified' | 'failed';

/** 'retainer' = brand-manager ongoing engagement (PRD §4.4). */
export type EngagementType = 'one_off' | 'retainer';

/** ⚠️ Configurable — Conflict Ledger C1–C3. Always read from config/platformFees. */
export interface PlatformFees {
  talentPct: number; // default 0.11 (unconfirmed)
  clientPct: number; // default 0.15 (unconfirmed)
}

/** Region-aware money. `amount` is in MINOR units (kobo, cents, pence…). */
export interface Money {
  amount: number;
  currency: string; // ISO 4217 (NGN, USD, GBP…)
}

export interface MediaAsset {
  id: string;
  kind: MediaKind; // audio prioritised for vo_artist (US-1)
  url: string;
  sizeBytes: number; // max 150MB, enforced at upload
  durationSec?: number;
}

/** "Add Booking Service Title" — niche-agnostic, never "Cast Role Title". */
export interface RateCard {
  id: string;
  serviceTitle: string;
  basePrice: Money;
  deliveryTimeline: string; // e.g. "3 days", "1 session"
}

export interface AvailabilityBlock {
  date: string; // ISO date
  slots: { start: string; end: string; booked: boolean }[];
}

export interface Creator {
  id: string;
  userType: 'talent';
  name: string;
  niche: Niche;
  bio: string;
  location: string; // country code from the launch-market list
  styleTags: string[]; // auto-generated by Thespian AI — vibe only, NOT KYC
  verification: VerificationState; // identity KYC via Smile Identity (C5) — the "Verified" badge
  celebrityBadge: boolean; // reputation badge earned via referral (§4.3) — SEPARATE from KYC
  referralCode: string; // drives the celebrity-badge/referral programme
  media: MediaAsset[];
  rateCards: RateCard[];
  availability: AvailabilityBlock[];
  createdAt: string;
  updatedAt: string;
}

export interface Client {
  id: string;
  userType: 'client';
  name: string;
  orgName?: string;
  orgType?: 'studio' | 'event' | 'brand' | 'church';
  location: string;
}

export interface Brief {
  id: string;
  clientId: string;
  projectName: string;
  projectType: string;
  nicheRequirements: Niche[];
  assets: MediaAsset[]; // scripts / references
  budget: Money; // from the budget slider (US-5)
  createdAt: string;
}

export interface Booking {
  id: string;
  creatorId: string;
  clientId: string;
  rateCardId: string;
  engagementType: EngagementType;
  slot: { date: string; start: string; end: string };
  recurrence?: string; // set when engagementType === 'retainer' (e.g. "monthly")
  base: Money;
  fees: { talentFee: Money; clientFee: Money }; // computed from PlatformFees — never literals
  state: BookingState;
  meetUrl?: string; // Google Meet link for the live call (US-8)
  createdAt: string;
}

export interface OrderRoom {
  id: string;
  bookingId: string;
  messages: Message[]; // text, voice, document, call events
  timeline: BookingState; // mirrors Booking.state for the escrow progress bar
  activeCallUrl?: string; // live Google Meet call in progress (US-8)
}

export interface Message {
  id: string;
  senderId: string;
  kind: 'text' | 'voice' | 'document' | 'call' | 'system'; // 'call' = live-call started/ended
  content: string;
  createdAt: string;
}

export interface WaitlistEntry {
  id: string;
  email: string;
  queueNumber: number; // "You are Number #{XYZ} in the verification queue"
  referralCode: string; // "Share your link to climb the roster"
}
